version: 1.0
type: protobuf
entities:
  hostname:
    entity: "sensor"
    attribute: "hostname"
  cve:
    entity: "vuln"
    attribute: "id"
  count:
    entity: "volume"
    attribute : "data"
relations:
  timestamp:
    relation: "has_detected"
    attribute: "timestamp"
    roles:
      vuln: "cve"
      volume: "metric"
      sensor: "device"